<?php include __DIR__ . '/../Header.php' ?>

<div class="container">
    <div class="card">
        <div class="card-body">
            <h1 style="box-sizing: border-box; margin: 0px 0px 21px; font-weight: bold; line-height: normal; font-size: 36px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: Montserrat, sans-serif; font-style: normal; color: rgb(0, 0, 0); -webkit-font-smoothing: antialiased; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Acuan pedoman kumparan sebagai media online di Indonesia</h1>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Kemerdekaan berpendapat, kemerdekaan berekspresi, dan kemerdekaan pers adalah hak asasi manusia yang dilindungi Pancasila, Undang-Undang Dasar 1945, dan Deklarasi Universal Hak Asasi Manusia PBB. Keberadaan media siber di Indonesia juga merupakan bagian dari kemerdekaan berpendapat, kemerdekaan berekspresi, dan kemerdekaan pers. Media siber memiliki karakter khusus sehingga memerlukan pedoman agar pengelolaannya dapat dilaksanakan secara profesional, memenuhi fungsi, hak, dan kewajibannya sesuai Undang-Undang Nomor 40 Tahun 1999 tentang Pers dan Kode Etik Jurnalistik. Untuk itu Dewan Pers bersama organisasi pers, pengelola media siber, dan masyarakat menyusun Pedoman Pemberitaan Media Siber sebagai berikut:</p>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>1. Ruang Lingkup</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media Siber adalah segala bentuk media yang menggunakan wahana internet dan melaksanakan kegiatan jurnalistik, serta memenuhi persyaratan Undang-Undang Pers dan Standar Perusahaan Pers yang ditetapkan Dewan Pers.</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Isi Buatan Pengguna (User Generated Content) adalah segala isi yang dibuat dan atau dipublikasikan oleh pengguna media siber, antara lain, artikel, gambar, komentar, suara, video dan berbagai bentuk unggahan yang melekat pada media siber, seperti blog, forum, komentar pembaca atau pemirsa, dan bentuk lain.</li>
            </ol>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>2. Verifikasi dan keberimbangan berita</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Pada prinsipnya setiap berita harus melalui verifikasi.</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Berita yang dapat merugikan pihak lain memerlukan verifikasi pada berita yang sama untuk memenuhi prinsip akurasi dan keberimbangan.</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Ketentuan dalam butir (a) di atas dikecualikan, dengan syarat:<ol style="box-sizing: border-box; margin: 20px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; list-style: none; counter-reset: my-sec-counter 0;">
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Berita benar-benar mengandung kepentingan publik yang bersifat mendesak;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Sumber berita yang pertama adalah sumber yang jelas disebutkan identitasnya, kredibel dan kompeten;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Subyek berita yang harus dikonfirmasi tidak diketahui keberadaannya dan atau tidak dapat diwawancarai;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Media memberikan penjelasan kepada pembaca bahwa berita tersebut masih memerlukan verifikasi lebih lanjut yang diupayakan dalam waktu secepatnya. Penjelasan dimuat pada bagian akhir dari berita yang sama, di dalam kurung dan menggunakan huruf miring.</li>
                    </ol>
                </li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Setelah memuat berita sesuai dengan butir (c), media wajib meneruskan upaya verifikasi, dan setelah verifikasi didapatkan, hasil verifikasi dicantumkan pada berita pemutakhiran (update) dengan tautan pada berita yang belum terverifikasi.</li>
            </ol>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>3. Isi Buatan Pengguna (User Generated Content)</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber wajib mencantumkan syarat dan ketentuan mengenai Isi Buatan Pengguna yang tidak bertentangan dengan Undang-Undang No. 40 tahun 1999 tentang Pers dan Kode Etik Jurnalistik, yang ditempatkan secara terang dan jelas.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber mewajibkan setiap pengguna untuk melakukan registrasi keanggotaan dan melakukan proses log-in terlebih dahulu untuk dapat mempublikasikan semua bentuk Isi Buatan Pengguna. Ketentuan mengenai log-in akan diatur lebih lanjut.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Dalam registrasi tersebut, media siber mewajibkan pengguna memberi persetujuan tertulis bahwa Isi Buatan Pengguna yang dipublikasikan:<ol style="box-sizing: border-box; margin: 20px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; list-style: none; counter-reset: my-sec-counter 0;">
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Tidak memuat isi bohong, fitnah, sadis dan cabul;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Tidak memuat isi yang mengandung prasangka dan kebencian terkait dengan suku, agama, ras, dan antargolongan (SARA), serta menganjurkan tindakan kekerasan;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Tidak memuat isi diskriminatif atas dasar perbedaan jenis kelamin dan bahasa, serta tidak merendahkan martabat orang lemah, miskin, sakit, cacat jiwa, atau cacat jasmani.</li>
                    </ol>
                </li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber memiliki kewenangan mutlak untuk mengedit atau menghapus Isi Buatan Pengguna yang bertentangan dengan butir (c).&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber wajib menyediakan mekanisme pengaduan Isi Buatan Pengguna yang dinilai melanggar ketentuan pada butir (c). Mekanisme tersebut harus disediakan di tempat yang dengan mudah dapat diakses pengguna.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber wajib menyunting, menghapus, dan melakukan tindakan koreksi setiap Isi Buatan Pengguna yang dilaporkan dan melanggar ketentuan butir (c), sesegera mungkin secara proporsional selambat-lambatnya 2 x 24 jam setelah pengaduan diterima.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber yang telah memenuhi ketentuan pada butir (a), (b), (c), dan (f) tidak dibebani tanggung jawab atas masalah yang ditimbulkan akibat pemuatan isi yang melanggar ketentuan pada butir (c). h. Media siber bertanggung jawab atas Isi Buatan Pengguna yang dilaporkan bila tidak mengambil tindakan koreksi setelah batas waktu sebagaimana tersebut pada butir (f).</li>
            </ol>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>4. Ralat, Koreksi, dan Hak Jawab</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Ralat, koreksi, dan hak jawab mengacu pada Undang-Undang Pers, Kode Etik Jurnalistik, dan Pedoman Hak Jawab yang ditetapkan Dewan Pers.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Ralat, koreksi dan atau hak jawab wajib ditautkan pada berita yang diralat, dikoreksi atau yang diberi hak jawab.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Di setiap berita ralat, koreksi, dan hak jawab wajib dicantumkan waktu pemuatan ralat, koreksi, dan atau hak jawab tersebut. d. Bila suatu berita media siber tertentu disebarluaskan media siber lain, maka:<ol style="box-sizing: border-box; margin: 20px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; list-style: none; counter-reset: my-sec-counter 0;">
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Tanggung jawab media siber pembuat berita terbatas pada berita yang dipublikasikan di media siber tersebut atau media siber yang berada di bawah otoritas teknisnya;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Koreksi berita yang dilakukan oleh sebuah media siber, juga harus dilakukan oleh media siber lain yang mengutip berita dari media siber yang dikoreksi itu;</li>
                        <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 32px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif;'>Media yang menyebarluaskan berita dari sebuah media siber dan tidak melakukan koreksi atas berita sesuai yang dilakukan oleh media siber pemilik dan atau pembuat berita tersebut, bertanggung jawab penuh atas semua akibat hukum dari berita yang tidak dikoreksinya itu.</li>
                    </ol>
                </li>
            </ol>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Sesuai dengan Undang-Undang Pers, media siber yang tidak melayani hak jawab dapat dijatuhi sanksi hukum pidana denda paling banyak Rp500.000.000 (Lima ratus juta rupiah).</p>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>5. Pencabutan Berita</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Berita yang sudah dipublikasikan tidak dapat dicabut karena alasan penyensoran dari pihak luar redaksi, kecuali terkait masalah SARA, kesusilaan, masa depan anak, pengalaman traumatik korban atau berdasarkan pertimbangan khusus lain yang ditetapkan Dewan Pers.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber lain wajib mengikuti pencabutan kutipan berita dari media asal yang telah dicabut.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Pencabutan berita wajib disertai dengan alasan pencabutan dan diumumkan kepada publik.</li>
            </ol>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>6. Iklan</h3>
            <ol style='box-sizing: border-box; margin: 0px 0px 40px; padding: 0px; border: 0px; outline: 0px; font-size: 14px; vertical-align: baseline; background: rgb(255, 255, 255); list-style: none; counter-reset: listStyle 0; color: rgb(118, 118, 118); font-family: "Red Hat Text", sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Media siber wajib membedakan dengan tegas antara produk berita dan iklan.&nbsp;</li>
                <li style='box-sizing: border-box; margin: 0px 0px 10px; padding: 0px 0px 0px 22px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: transparent; line-height: 28px; color: rgb(51, 51, 51); position: relative; font-family: "PT Serif", serif; counter-increment: listStyle 1;'>Setiap berita/artikel/isi yang merupakan iklan dan atau isi berbayar wajib mencantumkan keterangan &apos;advertorial&apos;, &apos;iklan&apos;, &apos;ads&apos;, &apos;sponsored&apos;, atau kata lain yang menjelaskan bahwa berita/artikel/isi tersebut adalah iklan.</li>
            </ol>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>7. Hak Cipta</h3>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Media siber wajib menghormati hak cipta sebagaimana diatur dalam peraturan perundang-undangan yang berlaku.</p>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>8. Pencantuman Pedoman</h3>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Media siber wajib mencantumkan Pedoman Pemberitaan Media Siber ini di medianya secara terang dan jelas.</p>
            <h3 style='box-sizing: border-box; margin: 0px 0px 20px; font-weight: normal; line-height: 30px; font-size: 26px; padding: 0px; border: 0px; outline: 0px; vertical-align: baseline; background: rgb(255, 255, 255); font-family: "Red Hat Text", sans-serif; -webkit-font-smoothing: antialiased; color: black; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>9. Sengketa</h3>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>Penilaian akhir atas sengketa mengenai pelaksanaan Pedoman Pemberitaan Media Siber ini diselesaikan oleh Dewan Pers.</p>
            <p style='box-sizing: border-box; margin: 0px 0px 21px; padding: 0px; border: 0px; outline: 0px; font-size: 18px; vertical-align: baseline; background: rgb(255, 255, 255); line-height: 28px; color: rgb(51, 51, 51); font-family: "PT Serif", serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;'>&nbsp;</p>
        </div>
    </div>
</div>

<?php include __DIR__ . '/../Footer.php' ?>